version: '3'
services:
  producer:
    build: producer
    depends_on:
      - redis
  worker:
    build: worker
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"



      